### ISSUE TITLE
Changing key id to be hexdigest(sha256(cjson(public_key)))

### ISSUE THREAD

**Issue by erickt** [heartsucker/rust-tuf#150]
Fuchsia' tuf implementation needs to be compatible with [go-tuf](https://github.com/flynn/go-tuf), which uses `hexdigest(sha256(cjson(public_key)))` for it's key id, which is currently required by the [spec section 4.2](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats). Would you be okay if I converted rust-tuf to be compliant by default, at least until [TAP 11](https://github.com/theupdateframework/taps/pull/74) is accepted? I could migrate the current key id algorithm behind a feature flag (or put the standard behind a feature flag, if you'd prefer that).

**Comment by heartsucker** [comment]
This would probably actually be annoying and a bit complex. You'd have to look and checkout how `go-tuf` does `cjson`, because as we can see from this issue https://github.com/theupdateframework/tuf/issues/457, it's not clear everyone agrees on what `cjson` even is.

Also when talking to TUF team, it seemed that compatibility wasn't guaranteed between impls and in fact wasn't even a goal from the spec, so I made some opinionated decision to clean up the metadata and key formats for more internal consistency. This crate as it stands is incompatible with `go-tuf` and the python impl in a number of ways.

**Comment by erickt** [comment]
Heh, I'm okay with annoying and a bit complex (see #151 😄).

Yeah, I've been tracking that issue. It's really unfortunate that cjson messed this up and now is now stuck at not actually being json-compatible. I agree with you on TAP 11, I'm just stuck figuring out how to slowly switch from go-tuf to rust-tuf. Fortunately though, it looks like go-tuf does have a proper cjson parser that only [escapes `"` and `\`](https://github.com/tent/canonical-json-go/blob/master/encode.go#L371-L404), so on that front I think it should be compatible with your implementation of cjson. Are you aware of any other incompatibilities? In the worst case we can maintain a long-lived fork of rust-tuf, but it'd be nice to avoid doing that if possible.
