### ISSUE TITLE
RSA key verification

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#2]
I know `ring` has some goodies in it, and at minimum we want to support RSASSA-PSS.

**Comment by tonychain** [comment]
I would definitely suggest using *ring*. I am less enthusiastic about RSA (even with PSS) although if the goal of this project is to be a reusable TUF implementation I suppose it makes sense, and *ring* has a decent RSA implementation.

**Comment by briansmith** [comment]
Note that the *ring* API is designed so that you can use RSA simply by swapping `signature::ED25519` in your code for `signature::RSA_PSS_2048_8192_SHA256`. So probably the best thing to do is to parameterize all the signature checking logic within rust-tuf with a `&'static signature::VerificationAlgorithm` parameter.

**Comment by heartsucker** [comment]
Note: This (very much most likely) depends on #3 or at least a better implementation of the `cjson` bits I implemented.

**Comment by heartsucker** [comment]
Update: progress can be found in the `rsa` branch.

**Comment by heartsucker** [comment]
Partially blocked by https://github.com/briansmith/ring/issues/530

**Comment by heartsucker** [comment]
Adding to version 0.1.0 because this is needed for testing something else.
