### ISSUE TITLE
Expired root metadata blocks updating current root metadata

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#49]
When attempting to get the most up to date root metadata, the client rebuilds the chain of trust, but in doing so, expired metadata will return an error and prevent the update from happening.

**Comment by trishankkarthik** [comment]
Good point. I thought I had specified this with [step 0.2 in the client update workflow](https://github.com/theupdateframework/tuf/blob/c1e72e0fdd092c5d71d52ffa345893b4a8013a25/docs/tuf-spec.txt#L942-L943), but it looks like I missed saying the same for step 1.5.

However, we should be careful here, because I think at least the last (or at least, the last one that an attacker may make available) root metadata file should not have expired.

@JustinCappos: what do you think?

**Comment by JustinCappos** [comment]
I agree with your assessment.  Please update the document to make it
clearer.
