### ISSUE TITLE
Spec - 4.2 - All RSA keys must be 2048 bits or more

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#9]

**Comment by briansmith** [comment]
If you use *ring* for this then it will be taken care of automatically since *ring*'s minimum is 2048 bits. This won't change transparently, as the minimum number of bits is part of the algorithm name. See https://briansmith.org/rustdoc/ring/signature/index.html#statics. So this will be done when #2 is done.

**Comment by heartsucker** [comment]
@briansmith Good to know. Once we have this implemented, we'll need to make a corresponding test vector to ensure that this property holds if the underlying lib is ever swapped out.
